name: frontegg_flutter
description: Flutter package for Frontegg services
version: 1.0.8
homepage: https://github.com/frontegg/frontegg-flutter
#publish_to: "https://pub.dartlang.org"

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^6.4.1
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  mockito: ^5.3.2

flutter:
  plugin:
    platforms:
      android:
        package: com.frontegg.flutter
        pluginClass: FronteggFlutterPlugin
      ios:
        pluginClass: FronteggFlutterPlugin
