name: frontegg
description: Flutter package for Frontegg services
version: 0.0.4
homepage: https://github.com/frontegg/frontegg-flutter

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.frontegg.flutter
        pluginClass: FronteggFlutterPlugin
      ios:
        pluginClass: FronteggFlutterPlugin
